### ISSUE TITLE
A l'example2 self.possibles hauria de ser un enter, és None

### ISSUE THREAD

**Issue by saludes** [rafelamer/examens-python#3]
1. Copio **examples2** a un nou directori
2. Em moc allí

```$ examen.py --examen=examen.tex --estudiants=estudiants.csv```

Dóna:
```
Traceback (most recent call last):
  File "/home/runner/Rafel/venv/bin/examen.py", line 623, in <module>
    main.main()
  File "/home/runner/Rafel/venv/bin/examen.py", line 618, in main
    self.generar_examens()
  File "/home/runner/Rafel/venv/bin/examen.py", line 435, in generar_examens
    llista = list(range(self.possibles))
TypeError: 'NoneType' object cannot be interpreted as an integer```

**Comment by saludes** [comment]
Uff! sembla que no he copiat tots els paràmetres!

Va bé.
